name: Execução dos testes de integração

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
